# Generated by Django 5.2.7 on 2025-12-05 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0002_alter_animal_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gmd_calculado_automatico', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('importacao', 'Importação')], default='manual', max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesagens', to='animais.animal')),
            ],
        ),
    ]
