# Generated by Django 5.2.7 on 2026-02-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesagem',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('cocho', 'Cocho'), ('pasto', 'Pasto')], max_length=10, null=True),
        ),
    ]
