# Generated by Django 5.2.7 on 2026-02-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesagens', '0002_pesagem_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='classificacao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
