# Generated by Django 5.2.7 on 2026-02-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0002_alter_lote_status_alter_lote_updated_at'),
        ('manejos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.CharField(max_length=100, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], default='F', max_length=1)),
                ('categoria', models.CharField(choices=[('bezerro', 'Bezerro'), ('novilho', 'Novilho'), ('vaca', 'Vaca'), ('touro', 'Touro')], default='novilho', max_length=20)),
                ('raca', models.CharField(blank=True, max_length=500, null=True)),
                ('origem', models.CharField(choices=[('compra', 'Compra'), ('nascimento', 'Nascimento'), ('terceiros', 'Terceiros')], default='compra', max_length=20)),
                ('idade', models.CharField(choices=[('maior_12_meses', 'Maior que 12 meses'), ('menor_12_meses', 'Menor que 12 meses')], default='menor_12_meses', max_length=20)),
                ('ganho_acumulado', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('score_rendimento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vendido', 'Vendido'), ('morto', 'Morto'), ('transferido', 'Transferido')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='lote.lote')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLoteAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('importacao', 'Importação')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
                ('lote_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_como_destino', to='lote.lote')),
                ('lote_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_como_origem', to='lote.lote')),
                ('manejo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='manejos.manejo')),
            ],
            options={
                'verbose_name_plural': 'Históricos de Lote de Animais',
                'ordering': ['-data', '-created_at'],
                'indexes': [models.Index(fields=['animal', 'data'], name='animais_his_animal__58b468_idx'), models.Index(fields=['lote_origem'], name='animais_his_lote_or_a7f374_idx'), models.Index(fields=['lote_destino'], name='animais_his_lote_de_b66c44_idx')],
            },
        ),
    ]
