# Generated by Django 5.2.7 on 2026-02-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.CharField(max_length=100, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Femea')], default='F', max_length=1)),
                ('categoria', models.CharField(choices=[('bezerro', 'Bezerro'), ('novilho', 'Novilho'), ('vaca', 'Vaca'), ('touro', 'Touro')], default='novilho', max_length=20)),
                ('raca', models.CharField(blank=True, max_length=500, null=True)),
                ('origem', models.CharField(choices=[('compra', 'Compra'), ('nascimento', 'Nascimento'), ('terceiros', 'Terceiros')], default='compra', max_length=20)),
                ('idade', models.CharField(choices=[('maior_12_meses', 'Maior que 12 meses'), ('menor_12_meses', 'Menor que 12 meses')], default='menor_12_meses', max_length=20)),
                ('ganho_acumulado', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('score_rendimento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vendido', 'Vendido'), ('morto', 'Morto'), ('transferido', 'Transferido')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLoteAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('importacao', 'Importação')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Históricos de Lote de Animais',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
