# Generated by Django 5.2.7 on 2025-12-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Macho'), ('M', 'Femea')], default='F', max_length=1)),
                ('categoria', models.CharField(choices=[('bezerro', 'Bezerro'), ('novilho', 'Novilho'), ('vaca', 'Vaca'), ('touro', 'Touro')], default='novilho', max_length=20)),
                ('raca', models.CharField(blank=True, max_length=500, null=True)),
                ('origem', models.CharField(choices=[('compra', 'Compra'), ('nascimento', 'Nascimento'), ('terceiros', 'Terceiros')], default='compra', max_length=20)),
                ('idade', models.CharField(choices=[('maior_12_meses', 'Maior que 12 meses'), ('menor_12_meses', 'Menor que 12 meses')], max_length=20)),
                ('ganho_acumulado', models.FloatField(default=0)),
                ('score_rendimento', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='lote.lote')),
            ],
        ),
    ]
