# Generated by Django 5.2.7 on 2026-02-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='lote.lote'),
        ),
        migrations.AddField(
            model_name='historicoloteanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.animal'),
        ),
        migrations.AddField(
            model_name='historicoloteanimal',
            name='lote_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_como_destino', to='lote.lote'),
        ),
        migrations.AddField(
            model_name='historicoloteanimal',
            name='lote_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_como_origem', to='lote.lote'),
        ),
        migrations.AddIndex(
            model_name='historicoloteanimal',
            index=models.Index(fields=['animal', 'data'], name='animais_his_animal__58b468_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoloteanimal',
            index=models.Index(fields=['lote_origem'], name='animais_his_lote_or_a7f374_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoloteanimal',
            index=models.Index(fields=['lote_destino'], name='animais_his_lote_de_b66c44_idx'),
        ),
    ]
