# Generated by Django 5.2.7 on 2026-02-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoloteanimal',
            name='manejo',
        ),
    ]
