# Generated by Django 5.2.7 on 2025-12-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='brinco',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(choices=[('maior_12_meses', 'Maior que 12 meses'), ('menor_12_meses', 'Menor que 12 meses')], default='menor_12_meses', max_length=20),
        ),
    ]
