# Generated by Django 5.2.7 on 2025-12-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('peso_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gmd_medio', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('raca_majoritaria', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('Fechado', 'Fechado'), ('vendido', 'Vendido')], default='ativo', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='fazendas.fazenda')),
            ],
        ),
    ]
