# Generated by Django 5.2.7 on 2026-01-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('fechado', 'Fechado'), ('vendido', 'Vendido')], default='ativo', max_length=100),
        ),
        migrations.AlterField(
            model_name='lote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
