# Generated by Django 5.2.7 on 2025-11-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioempresa',
            name='role',
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('produtor', 'Produtor')], default='admin', max_length=8),
            preserve_default=False,
        ),
    ]
