# Generated by Django 5.2.7 on 2026-02-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazendas', '0001_initial'),
        ('produtor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='produtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtor.produtor'),
        ),
    ]
