# Generated by Django 5.2.7 on 2026-02-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('move_lote', models.BooleanField(default=False)),
                ('exige_lote_origem', models.BooleanField(default=False)),
                ('exige_lote_destino', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animais', models.ManyToManyField(related_name='manejos', to='animais.animal')),
                ('lote_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manejos_destino', to='lote.lote')),
                ('lote_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manejos_origem', to='lote.lote')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='manejos.tipomanejo')),
            ],
        ),
    ]
