# Generated by Django 5.2.7 on 2025-12-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0003_alter_animal_brinco_alter_animal_idade'),
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('peso', models.FloatField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='animais.animal')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lote.lote')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manejos', to='manejos.tipomanejo')),
            ],
        ),
    ]
