# Generated by Django 5.2.7 on 2025-12-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_endereco'),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
